// Generated by tools/generate-pages.mjs — do not edit.
export const CURRICULUM = [
  {
    "slug": "setup",
    "number": 1,
    "title": "The Setup",
    "kicker": "Fundamentals",
    "tagline": "Most of the shot is settled before you ever move the club.",
    "summary": "Grip, stance, posture, alignment and ball position. You can check all five while you're still standing over the ball, and if they're right the swing gets a fair chance before it starts.",
    "duration": "20 min",
    "level": "Beginner to Intermediate",
    "next": "swing",
    "image": "setup"
  },
  {
    "slug": "swing",
    "number": 2,
    "title": "The Full Swing",
    "kicker": "Foundations",
    "tagline": "Ten places to check a swing that only lasts a second.",
    "summary": "The full swing as one motion, read through the P1 to P10 checkpoints. Plane, sequence, width, tempo, impact, and what your finish can tell you about all of it.",
    "duration": "35 min",
    "level": "Beginner to Intermediate",
    "next": "driver",
    "image": "swing"
  },
  {
    "slug": "driver",
    "number": 3,
    "title": "The Driver",
    "kicker": "Full swing",
    "tagline": "The one club in the bag you hit on the way up.",
    "summary": "Why the driver is the club you strike on the upswing, how to set up for it, and how launch, spin and where you hit the face turn clubhead speed into carry.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "irons",
    "image": "driver"
  },
  {
    "slug": "irons",
    "number": 4,
    "title": "Irons",
    "kicker": "Full swing",
    "tagline": "Hit down, take the divot after, watch it rise.",
    "summary": "How the descending strike works, with the low point ahead of the ball and the hands and weight forward at impact, plus honest distance gapping and how to control your trajectory.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "wedges",
    "image": "irons"
  },
  {
    "slug": "wedges",
    "number": 5,
    "title": "Wedges & Pitching",
    "kicker": "Short game",
    "tagline": "Turn through, keep the hands soft, let the loft do the work.",
    "summary": "Build a pitching motion the body drives, then use the clock system to turn four wedges into twelve carry numbers you can trust from 30 to 100 yards.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "chipping",
    "image": "wedges"
  },
  {
    "slug": "chipping",
    "number": 6,
    "title": "Chipping",
    "kicker": "Short game",
    "tagline": "A putt with loft, landed on a spot.",
    "summary": "Treat the chip as a putting stroke with loft, pick a landing spot every time, and use carry-to-roll ratios to choose the club that gets the ball rolling soonest.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "bunker",
    "image": "chipping"
  },
  {
    "slug": "bunker",
    "number": 7,
    "title": "Bunker Play",
    "kicker": "Short game",
    "tagline": "Hit the sand, not the ball, and keep turning.",
    "summary": "Get to know bounce, open the face before you grip, splash a dollar bill of sand from two inches behind the ball, and finish every single swing.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "putting",
    "image": "bunker"
  },
  {
    "slug": "putting",
    "number": 8,
    "title": "Putting",
    "kicker": "On the green",
    "tagline": "Square face, quiet wrists, pace that holds its line.",
    "summary": "Setup, the pendulum stroke, launch and roll, pace and the lag zone, reading slope to an aim point, and three drills that make it all repeatable.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "ball-flight",
    "image": "putting"
  },
  {
    "slug": "ball-flight",
    "number": 9,
    "title": "The Ball Flight Laws",
    "kicker": "The lab",
    "tagline": "The face starts it, the path bends it.",
    "summary": "The modern ball flight laws: the face sets the start, face-to-path sets the curve, gear effect, spin loft, why you slice, and how to diagnose yourself from your divot and your flight.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "setup",
    "image": "ball-flight"
  }
];
