// Generated by tools/generate-pages.mjs — do not edit.
export const CURRICULUM = [
  {
    "slug": "setup",
    "number": 1,
    "title": "The Setup",
    "kicker": "Fundamentals",
    "tagline": "Everything the swing does, the setup decides first.",
    "summary": "Grip, stance, posture, alignment and ball position: the five static checkpoints that give every swing a fair chance before the club ever moves.",
    "duration": "20 min",
    "level": "Beginner to Intermediate",
    "next": "swing",
    "image": "setup"
  },
  {
    "slug": "swing",
    "number": 2,
    "title": "The Full Swing",
    "kicker": "Foundations",
    "tagline": "One motion, ten checkpoints, one moment of truth.",
    "summary": "The full swing as a single motion, read through the P1 to P10 checkpoints: plane, sequence, width, tempo, impact, and what your finish tells you.",
    "duration": "35 min",
    "level": "Beginner to Intermediate",
    "next": "driver",
    "image": "swing"
  },
  {
    "slug": "driver",
    "number": 3,
    "title": "The Driver",
    "kicker": "Full swing",
    "tagline": "The one club you swing up, not down.",
    "summary": "Why the driver is the only club you strike on the upswing, how to set up for it, and how launch, spin and strike location turn clubhead speed into carry.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "irons",
    "image": "driver"
  },
  {
    "slug": "irons",
    "number": 4,
    "title": "Irons",
    "kicker": "Full swing",
    "tagline": "Hit down, take the divot after, watch it rise.",
    "summary": "The descending strike that makes irons work: low point ahead of the ball, shaft lean and weight forward at impact, plus honest distance gapping and trajectory control.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "wedges",
    "image": "irons"
  },
  {
    "slug": "wedges",
    "number": 5,
    "title": "Wedges & Pitching",
    "kicker": "Short game",
    "tagline": "Turn through, stay soft, let the loft work.",
    "summary": "Build a body-driven pitching motion, then use the clock system to turn four wedges into twelve reliable carry numbers you can trust from 30 to 100 yards.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "chipping",
    "image": "wedges"
  },
  {
    "slug": "chipping",
    "number": 6,
    "title": "Chipping",
    "kicker": "Short game",
    "tagline": "A putt with loft, landed on a spot.",
    "summary": "Learn the chip as a lofted putting stroke, pick a landing spot every time, and use carry-to-roll ratios to choose the club that gets the ball rolling soonest.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "bunker",
    "image": "chipping"
  },
  {
    "slug": "bunker",
    "number": 7,
    "title": "Bunker Play",
    "kicker": "Short game",
    "tagline": "Hit the sand, not the ball, and keep turning.",
    "summary": "Understand bounce, open the face before you grip, splash a dollar bill of sand from two inches behind the ball, and finish every swing.",
    "duration": "25 min",
    "level": "Beginner to Intermediate",
    "next": "putting",
    "image": "bunker"
  },
  {
    "slug": "putting",
    "number": 8,
    "title": "Putting",
    "kicker": "On the green",
    "tagline": "Square face, quiet wrists, pace that holds its line.",
    "summary": "Setup, the pendulum stroke, launch and roll, pace and the lag zone, reading slope to an aim point, and three drills that make it repeatable.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "ball-flight",
    "image": "putting"
  },
  {
    "slug": "ball-flight",
    "number": 9,
    "title": "The Ball Flight Laws",
    "kicker": "The lab",
    "tagline": "The face starts it, the path bends it.",
    "summary": "The modern ball flight laws: the face sets the start, face-to-path sets the curve, gear effect, spin loft, why a slice happens, and how to diagnose yourself from divot and flight.",
    "duration": "30 min",
    "level": "Beginner to Intermediate",
    "next": "setup",
    "image": "ball-flight"
  }
];
