// How each drill is shown on the swing model: a program (what the golfer does), a club preset,
// props on the ground, and a camera. Keyed by "<lesson slug>:<drill name>".
export const DRILL_VIZ = {
  'ball-flight:Two-gate start line': { program: 'full', club: 'iron', props: ['tee-gate'], camera: 'down-the-line', note: 'Start the ball through the gate' },
  'ball-flight:Alignment-stick path check': { program: 'full', club: 'iron', props: ['stick-outside'], camera: 'overhead', note: 'Read the divot against the stick' },
  'ball-flight:Nine flights on purpose': { program: 'full', club: 'iron', props: [], camera: 'three-quarter', note: 'Call the shape, then hit it' },
  'ball-flight:Foot-spray strike map': { program: 'full', club: 'driver', props: [], camera: 'face-on', note: 'Check the strike after five' },
  'bunker:Line in the sand': { program: 'pitch', club: 'wedge', props: ['sand-line'], camera: 'down-the-line', note: 'Splash the line, not the ball' },
  'bunker:Dollar bill divot': { program: 'pitch', club: 'wedge', props: ['bill'], camera: 'three-quarter', note: 'Enter at the back of the bill' },
  'bunker:Ball on a buried tee': { program: 'pitch', club: 'wedge', props: ['buried-tee'], camera: 'face-on', note: 'Clip the tee out from under it' },
  'bunker:Three-length ladder': { program: 'ladder', club: 'wedge', props: [], camera: 'face-on', note: 'Same speed, three lengths' },
  'chipping:Landing spot towel': { program: 'chip', club: 'chip', props: ['towel-landing'], camera: 'three-quarter', note: 'Land it on the towel' },
  'chipping:Three clubs, one spot': { program: 'chip', club: 'chip', props: ['towel-landing'], camera: 'three-quarter', note: 'Same spot, three clubs' },
  'chipping:Alignment stick anti-flip': { program: 'chip', club: 'chip', props: ['stick-grip'], camera: 'face-on', note: 'The stick never touches your side' },
  'chipping:Trail hand only': { program: 'chip', club: 'chip', props: [], camera: 'face-on', hideLeadArm: true, note: 'Trail hand drives the chest through' },
  'driver:Tee only': { program: 'full', club: 'driver', props: [], camera: 'face-on', hideBall: true, note: 'Clip the tee on the way up' },
  'driver:Headcover gate': { program: 'full', club: 'driver', props: ['headcover'], camera: 'down-the-line', note: 'Miss the cover from the inside' },
  'driver:Step drill': { program: 'step', club: 'driver', props: [], camera: 'face-on', note: 'Step, then swing' },
  'driver:Face map': { program: 'full', club: 'driver', props: [], camera: 'face-on', note: 'Ten balls, then read the marks' },
  'irons:Line drill': { program: 'full', club: 'iron', props: ['ground-line'], camera: 'down-the-line', note: 'Divot starts at the line' },
  'irons:Nine to three': { program: 'nine-to-three', club: 'iron', props: [], camera: 'face-on', note: 'Lead arm 9, trail arm 3' },
  'irons:Lead foot only': { program: 'full', club: 'iron', props: [], camera: 'face-on', trailFootBack: true, note: 'Weight lives on the lead side' },
  'irons:Gapping session': { program: 'full', club: 'iron', props: [], camera: 'three-quarter', note: 'Ten balls per club, write the carry down' },
  'putting:Gate drill': { program: 'putt', club: 'putter', props: ['tee-gate-putt'], camera: 'down-the-line', note: 'Roll it through the gate' },
  'putting:Ladder drill': { program: 'putt', club: 'putter', props: [], camera: 'face-on', note: 'Each putt a little further' },
  'putting:Clock drill': { program: 'putt', club: 'putter', props: [], camera: 'face-on', note: 'Twelve putts around the hole' },
  'putting:Line-roll check': { program: 'putt', club: 'putter', props: ['ground-line'], camera: 'down-the-line', note: 'Watch the line roll true' },
  'setup:Feet together, step out': { program: 'step', club: 'iron', props: [], camera: 'face-on', note: 'Feet together, then step to width' },
  'setup:Two-stick station': { program: 'address', club: 'iron', props: ['stick-outside', 'stick-feet'], camera: 'overhead', note: 'Railroad tracks: body parallel left' },
  'setup:Mirror posture': { program: 'address', club: 'iron', props: [], camera: 'down-the-line', note: 'Hinge from the hips, arms hang' },
  'setup:Grip rebuild': { program: 'address', club: 'iron', props: [], camera: 'face-on', note: 'Rebuild it the same way every time' },
  'swing:Mirror checkpoints': { program: 'checkpoints', club: 'iron', props: [], camera: 'down-the-line', note: 'Stop at P2, P4 and P7' },
  'swing:Step-through sequence': { program: 'step', club: 'iron', props: [], camera: 'face-on', note: 'The step starts the downswing' },
  'swing:Pump to P6': { program: 'pump', club: 'iron', props: [], camera: 'down-the-line', note: 'Pump twice, then swing through' },
  'swing:Three-to-one count': { program: 'slow', club: 'iron', props: [], camera: 'face-on', note: 'One-two-three back, one down' },
  'wedges:Clock calibration': { program: 'ladder', club: 'wedge', props: [], camera: 'face-on', note: '7:30, 9:00, 10:30' },
  'wedges:Towel low point': { program: 'pitch', club: 'wedge', props: ['towel-behind'], camera: 'down-the-line', note: 'Miss the towel behind the ball' },
  'wedges:Connection glove': { program: 'pitch', club: 'wedge', props: ['glove'], camera: 'face-on', note: 'Keep the glove under the lead arm' },
  'wedges:Trajectory ladder': { program: 'pitch', club: 'wedge', props: [], camera: 'three-quarter', note: 'Low, medium, high with one club' },
};
